spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gmlcms11

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

## MariaDB Configuration
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#
#  # JPA Configuration
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: validate
